#profiles.yml
default:
  outputs:
    dev:
      account: CWLLSWU-ED28213 #change for your account
      database: DBT_DEV_DB
      password: dbtuser
      role: DBT_ROLE
      schema: JM
      threads: 1
      type: snowflake
      user: DBT_USER
      warehouse: DBT_WH
  target: dev
  
